version: "3.0"

expectations:
  population_size: 1000

actions:
  generate_dataset:
    run: >
      ehrql-dev:v2
        generate-dataset
        --output output/dataset.csv
        analysis/dataset_definition.py
    env:  
      EHRQL_ISOLATE_USER_CODE: never  
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv

  count_by_age:
    run: >
      python:latest
        python analysis/count_by_age.py
    needs: [generate_dataset]
    outputs:
      moderately_sensitive:
        count: output/count_by_age.csv
